[project]

## optional, file containing Hark code to be deployed
hark_file = "service.hk"

## optional, location of Python source:
python_src = "src"

[instance]

## optional, extra layers to use (maximum of 4)
extra_layers = [
  # Layer from: https://github.com/keithrozario/Klayers
  "arn:aws:lambda:eu-west-2:770693421928:layer:Klayers-python38-Pillow:4"
]

## optional, location of Python dependencies:
# python_requirements = "requirements.txt"

## optional, lambda function timeout (s)
lambda_timeout = 30

## optional, lambda function memory (MB)
lambda_memory = 512

## optional, file with lambda environment variables
# env = "hark_env.txt"

s3_access = [
  "hark-example-data"
]

managed_buckets = [
  "hark-example-data"
]
