[service]

## optional, deployment region (defaults to AWS_DEFAULT_REGION):
region = "eu-west-2"

## optional, file containing Teal code to be deployed
teal_file = "service.tl"

## optional, location of Python source:
python_src = "src"

## optional, extra layers to use (maximum of 4)
extra_layers = [
  # Layer from: https://github.com/keithrozario/Klayers
  "arn:aws:lambda:eu-west-2:770693421928:layer:Klayers-python38-Pillow:4"
]

## optional, location of Python dependencies:
# python_requirements = "requirements.txt"

## optional, lambda function timeout (s)
# lambda_timeout = 240

## optional, lambda function timeout (s)
lambda_memory = 512

## optional
# data_dir

## optional, enable read/write to one or more s3 buckets
s3_access = [
  "teal-examples-data"
]

## optional, file with lambda environment variables
# env = "teal_env.txt"
