[project]

## optional, file containing Teal code to be deployed
teal_file = "hello.tl"

## optional, location of Python source:
python_src = "src"

[instance]

## optional, extra layers to use (maximum of 4)
extra_layers = [
  # Layer from: https://github.com/keithrozario/Klayers
]

## optional, location of Python dependencies:
# python_requirements = "requirements.txt"

## optional, lambda function timeout (s)
lambda_timeout = 20

## optional, lambda function memory (MB)
lambda_memory = 128

## optional, file with lambda environment variables
# env = "teal_env.txt"

