# https://github.com/serverless/examples/tree/master/aws-python-rest-api-with-pynamodb

service: test

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: python3.8
  region: eu-west-2
  environment:
    RESOURCE_PREFIX: ${self:service}-${opt:stage, self:provider.stage}
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}-c9-sessions
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

package:
  exclude:
    - init.sh
    - deps.sh
    - deploy.sh
    - manual.sh
    - libs
    - src

layers:
  src:
    path: ./src
  libs:
    path: ./libs


functions:
  set_exe:
    handler: c9.executors.awslambda.set_exe
    layers:
      - { Ref: LibsLambdaLayer }
      - { Ref: SrcLambdaLayer }
    events:
      - http:
          path: set_exe
          method: post
          cors: true

  new:
    handler: c9.executors.awslambda.new
    layers:
      - { Ref: LibsLambdaLayer }
      - { Ref: SrcLambdaLayer }
    events:
      - http:
          path: new
          method: post
          cors: true

  resume:
    handler: c9.executors.awslambda.resume
    layers:
      - { Ref: LibsLambdaLayer }
      - { Ref: SrcLambdaLayer }
    events:
      - http:
          path: resume
          method: post
          cors: true


resources:
  Resources:

    # MountainsTest:
    #   Type: "AWS::SQS::Queue"
    #   Properties:
    #     QueueName: "MountainsTest"

    SessionTable:
      Type: 'AWS::DynamoDB::Table'
      ## Optional - uncomment this:
      # DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: todo_id
            AttributeType: S
        KeySchema:
          - AttributeName: todo_id
            KeyType: HASH
        ## Optional - uncomment this:
        # ProvisionedThroughput:
        #   ReadCapacityUnits: 1
        #   WriteCapacityUnits: 1
        BillingMode: PAY_PER_REQUEST
