# https://github.com/rust-lang/mdBook/blob/master/book-example/src/format/config.md
[book]
authors = ["Ric da Silva"]
language = "en"
multilingual = false
src = "src"
title = "The C9 Language"

[output.html]
curly_quotes = true

[output.linkcheck]
