
name: Build

on:
  push:
    branches: [ master, ci-dev ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude src/hark_lang/hark_parser/parser.py
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v6

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install pytest poetry
        poetry export --dev -f requirements.txt > requirements.txt
        pip install -r requirements.txt

    - name: Fast tests
      env:
        AWS_ACCESS_KEY_ID: foo
        AWS_SECRET_ACCESS_KEY: bar
        AWS_DEFAULT_REGION: eu-west-2
        DYNAMODB_ENDPOINT: http://localhost:9000
        PYTHONPATH: src
        ENABLE_IMPORT_BUILTIN: yep
      run: |
        mkdir -p logs
        wget -q http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz -O /tmp/dynamodb_local_latest.tar.gz
        tar -xzf /tmp/dynamodb_local_latest.tar.gz -C /tmp
        java -Djava.library.path=/tmp/DynamoDBLocal_lib -jar /tmp/DynamoDBLocal.jar -inMemory -port 9000 &
        sleep 2
        pytest -v -k "not ddb_processes" --runslow
