[service]

## optional, deployment region (defaults to AWS_DEFAULT_REGION):
region = "eu-west-2"

## optional, file containing Teal code to be deployed
teal_file = "video.tl"

## optional, location of Python source:
python_src = "src"

## optional, extra layers to use (maximum of 4)
extra_layers = [
  # Layer from: https://github.com/keithrozario/Klayers
  # ARNs: https://github.com/keithrozario/Klayers/blob/master/deployments/python3.8/arns/eu-west-2.csv
  "arn:aws:lambda:eu-west-2:770693421928:layer:Klayers-python38-ffmpeg-python:1"
]

## optional, lambda function timeout (s)
# lambda_timeout = 240

## optional, lambda function memory (MB)
lambda_memory = 512

## optional, buckets that `teal deploy` manages. Don't ever remove items!!
managed_buckets = [
  "teal-examples-data"
]

## optional, trigger a Teal function on upload to a bucket
upload_triggers = [
  # bucket, prefix (e.g. "images/"), suffix (e.g. ".jpg")
  ["teal-examples-data", "", ".txt"]
]

## optional, enable read/write to one or more s3 buckets
s3_access = [
  "teal-examples-data"
]
